<?php

namespace CryptoSm\Tests;

use PHPUnit\Framework\TestCase;
use CryptoSm\SM4\Sm4;
use CryptoSm\SM4\Sm4Options;
use CryptoSm\Exception\InvalidKeyException;

class Sm4Test extends TestCase
{
    private string $key = '0123456789abcdeffedcba9876543210';
    private string $iv = 'fedcba98765432100123456789abcdef';

    public function testSm4EncryptReturnsHex()
    {
        $msg = 'hello world! test';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $this->assertNotEmpty($encrypted);
        $this->assertTrue(ctype_xdigit($encrypted));
    }

    public function testSm4DecryptReturnsString()
    {
        $msg = 'hello world! test message12345';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);

        $this->assertNotEmpty($decrypted);
    }

    public function testSm4KeyValidation()
    {
        $this->expectException(InvalidKeyException::class);

        $msg = 'test';
        $key = '0123456789abcdeffedcba987654321';

        Sm4::encrypt($msg, $key);
    }

    public function testSm4NoPadding()
    {
        $msg = '1234567890123456';
        $options = (new Sm4Options())->setMode('ecb')->setPadding('none');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $this->assertEquals(32, strlen($encrypted));

        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);
        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4CbcMode()
    {
        $msg = 'hello world test';
        $options = (new Sm4Options())->setMode('cbc')->setIv($this->iv);

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $this->assertNotEmpty($encrypted);

        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);
        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4CbcDefaultMode()
    {
        // CBC is now the default mode - requires IV
        $msg = 'hello world test';
        $options = (new Sm4Options())->setIv($this->iv);

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $this->assertNotEmpty($encrypted);

        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);
        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4EcbMode()
    {
        $msg = 'hello world test';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $this->assertNotEmpty($encrypted);

        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);
        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4EncryptDecrypt()
    {
        $msg = 'Hello, SM4!';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);

        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4EncryptDecryptChinese()
    {
        $msg = '你好，SM4！';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);

        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4EncryptDecryptLongMessage()
    {
        $msg = str_repeat('Long message test. ', 100);
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);

        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4CbcDefaultIvAutoGenerated()
    {
        // CBC is the default mode — IV is auto-generated in Sm4Options constructor
        $msg = 'test message';
        $options = new Sm4Options();

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $this->assertNotEmpty($encrypted);

        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);
        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4SetIvValidation()
    {
        $this->expectException(InvalidKeyException::class);

        (new Sm4Options())->setIv('invalid-iv');
    }

    public function testSm4InvalidKeyLength()
    {
        $this->expectException(InvalidKeyException::class);
        $this->expectExceptionMessage('Key must be 128 bits (32 hex chars)');

        $msg = 'test message';
        $key = 'shortkey';

        Sm4::encrypt($msg, $key);
    }

    public function testSm4EmptyMessage()
    {
        $msg = '';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted = Sm4::encrypt($msg, $this->key, $options);
        $decrypted = Sm4::decrypt($encrypted, $this->key, $options);

        $this->assertEquals($msg, $decrypted);
    }

    public function testSm4DifferentKeysProduceDifferentResults()
    {
        $msg = 'test message';
        $key2 = 'fedcba98765432100123456789abcdef';
        $options = (new Sm4Options())->setMode('ecb');

        $encrypted1 = Sm4::encrypt($msg, $this->key, $options);
        $encrypted2 = Sm4::encrypt($msg, $key2, $options);

        $this->assertNotEquals($encrypted1, $encrypted2);
    }

    public function testSm4OptionsChainable()
    {
        $options = new Sm4Options();

        $result = $options->setPadding('none')->setMode('cbc')->setIv('000102030405060708090a0b0c0d0e0f');

        $this->assertInstanceOf(Sm4Options::class, $result);
        $this->assertEquals('none', $options->getPadding());
        $this->assertEquals('cbc', $options->getMode());
        $this->assertEquals('000102030405060708090a0b0c0d0e0f', $options->getIv());
    }

    public function testSm4HexToBytesStatic()
    {
        $hex = '0123456789abcdef';
        $bytes = Sm4::hexToBytesStatic($hex);

        $this->assertCount(8, $bytes);
    }

    public function testSm4MultipleEncryptDecrypt()
    {
        $messages = [
            'short',
            'medium length message',
            'a bit longer message for testing',
            str_repeat('x', 100),
            '中文测试消息'
        ];
        $options = (new Sm4Options())->setMode('ecb');

        foreach ($messages as $msg) {
            $encrypted = Sm4::encrypt($msg, $this->key, $options);
            $decrypted = Sm4::decrypt($encrypted, $this->key, $options);
            $this->assertEquals($msg, $decrypted, "Failed for message: $msg");
        }
    }

    public function testSm4CbcModeDifferentIvProduceDifferentResults()
    {
        $msg = 'test message';
        $iv2 = '0123456789abcdeffedcba9876543210';

        $options1 = (new Sm4Options())->setMode('cbc')->setIv($this->iv);
        $options2 = (new Sm4Options())->setMode('cbc')->setIv($iv2);

        $encrypted1 = Sm4::encrypt($msg, $this->key, $options1);
        $encrypted2 = Sm4::encrypt($msg, $this->key, $options2);

        $this->assertNotEquals($encrypted1, $encrypted2);
    }

    public function testSm4Pkcs5Padding()
    {
        $options = (new Sm4Options())->setMode('ecb');

        $msg1 = '1';
        $encrypted1 = Sm4::encrypt($msg1, $this->key, $options);
        $this->assertEquals(32, strlen($encrypted1));

        $msg16 = '1234567890123456';
        $encrypted16 = Sm4::encrypt($msg16, $this->key, $options);
        $this->assertEquals(64, strlen($encrypted16));
    }

    public function testSm4ImplementsCipherInterface()
    {
        $this->assertInstanceOf(\CryptoSm\Interface\CipherInterface::class, new Sm4());
    }

    public function testSm4OptionsInvalidMode()
    {
        $this->expectException(InvalidKeyException::class);
        (new Sm4Options())->setMode('cfb');
    }

    public function testSm4OptionsInvalidPadding()
    {
        $this->expectException(InvalidKeyException::class);
        (new Sm4Options())->setPadding('invalid');
    }

    public function testSm4InvalidCiphertextHex()
    {
        $this->expectException(InvalidKeyException::class);
        Sm4::decrypt('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', $this->key, (new Sm4Options())->setMode('ecb'));
    }
}
